<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BukuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('buku')->insert([
            [
                'title' => 'Bahasa Indonesia',
                'penulis' => 1, // Sesuaikan dengan ID di tabel penulis
                'penerbit' => 1, // Sesuaikan dengan ID di tabel penerbit
                'terbit' => '2023-01-01',
                'deskripsi' => 'Yes it is',
                'sinopsis' => 'You start we end',
                'genre' => 1, // Sesuaikan dengan ID di tabel genre
                'stock' => 10,
                'gambar_buku' => 'indonesia7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bahasa Inggris',
                'penulis' => 2,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'english7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Informatika',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'informatika7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Matematika',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'mat7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ilmu Pengetahuan Alam',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'ipa7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ilmu Pengetahuan Sosial',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'ips7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pendidikan Kewarganegaraan',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'pkn7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bahasa Indonesia',
                'penulis' => 1, // Sesuaikan dengan ID di tabel penulis
                'penerbit' => 1, // Sesuaikan dengan ID di tabel penerbit
                'terbit' => '2023-01-01',
                'deskripsi' => 'Yes it is',
                'sinopsis' => 'You start we end',
                'genre' => 1, // Sesuaikan dengan ID di tabel genre
                'stock' => 10,
                'gambar_buku' => 'indonesia8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bahasa Inggris',
                'penulis' => 2,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'english8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Informatika',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'informatika8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Matematika',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'mat8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ilmu Pengetahuan Alam',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'ipa8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ilmu Pengetahuan Sosial',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'ips8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pendidikan Kewarganegaraan',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'pkn8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bahasa Indonesia',
                'penulis' => 1, // Sesuaikan dengan ID di tabel penulis
                'penerbit' => 1, // Sesuaikan dengan ID di tabel penerbit
                'terbit' => '2023-01-01',
                'deskripsi' => 'Yes it is',
                'sinopsis' => 'You start we end',
                'genre' => 1, // Sesuaikan dengan ID di tabel genre
                'stock' => 10,
                'gambar_buku' => 'indonesia9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bahasa Inggris',
                'penulis' => 2,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'english9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Informatika',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'informatika9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Matematika',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'mat9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ilmu Pengetahuan Alam',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'ipa9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ilmu Pengetahuan Sosial',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'ips9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pendidikan Kewarganegaraan',
                'penulis' => 1,
                'penerbit' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre' => 2,
                'stock' => 5,
                'gambar_buku' => 'pkn9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
