<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BukuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('buku')->insert([
            [
                'kode_buku' => 'SATUI',
                'isbn' => '9786231183682',
                'title' => 'Bahasa Indonesia',
                'penulis_id' => 1, // Sesuaikan dengan ID di tabel penulis_id
                'penerbit_id' => 1, // Sesuaikan dengan ID di tabel penerbit_id
                'terbit' => '2023-01-01',
                'deskripsi' => 'Bahasa Indonesia: untuk SMP/MTS Kelas VII (Edisi Revisi)',
                'sinopsis' => 'Bahasa Indonesia: untuk SMP/MTS Kelas VII (Edisi Revisi)',
                'genre_id' => 2, // Sesuaikan dengan ID di tabel genre_id
                'stock' => 10,
                'gambar_buku' => 'indonesia7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'SATUE',
                'isbn' => '9786022448853',
                'title' => 'Bahasa Inggris',
                'penulis_id' => 2,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'English for Nusantara untuk SMP/MTs Kelas VII',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'english7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'SATUT',
                'isbn' => '9786230955853',
                'title' => 'Informatika',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'informatika7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'SATUM',
                'isbn' => '9786230955853',
                'title' => 'Matematika',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'mat7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'SATUA',
                'isbn' => '9786231184573',
                'title' => 'Ilmu Pengetahuan Alam',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Ilmu Pengetahuan Alam untuk SMP/MTs Kelas VII (Edisi Revisi)',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'ipa7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'SATUS',
                'isbn' => '9786230955853',
                'title' => 'Ilmu Pengetahuan Sosial',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'ips7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'SATUP',
                'isbn' => '9786230955853',
                'title' => 'Pendidikan Kewarganegaraan',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'pkn7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAIN',
                'isbn' => '9786022446224',
                'title' => 'Bahasa Indonesia',
                'penulis_id' => 1, // Sesuaikan dengan ID di tabel penulis_id
                'penerbit_id' => 1, // Sesuaikan dengan ID di tabel penerbit_id
                'terbit' => '2023-01-01',
                'deskripsi' => 'Yes it is',
                'sinopsis' => 'Bahasa Indonesia untuk SMP Kelas VIII',
                'genre_id' => 2, // Sesuaikan dengan ID di tabel genre_id
                'stock' => 10,
                'gambar_buku' => 'indonesia8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAEN',
                'isbn' => '9786024279417',
                'title' => 'Bahasa Inggris',
                'penulis_id' => 2,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'English for Nusantara untuk SMP/MTs Kelas VIII',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'english8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAIF',
                'isbn' => '9786230955853',
                'title' => 'Informatika',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'informatika8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAMK',
                'isbn' => '9786230955853',
                'title' => 'Matematika',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'mat8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAPA',
                'isbn' => '9786022447948',
                'title' => 'Ilmu Pengetahuan Alam',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Ilmu Pengetahuan Alam untuk SMP Kelas VIII',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'ipa8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAPS',
                'isbn' => '9786230955853',
                'title' => 'Ilmu Pengetahuan Sosial',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'ips8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAPN',
                'isbn' => '9786230955853',
                'title' => 'Pendidikan Kewarganegaraan',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'pkn8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAI',
                'isbn' => '9786022446361',
                'title' => 'Bahasa Indonesia',
                'penulis_id' => 1, // Sesuaikan dengan ID di tabel penulis_id
                'penerbit_id' => 1, // Sesuaikan dengan ID di tabel penerbit_id
                'terbit' => '2023-01-01',
                'deskripsi' => 'Yes it is',
                'sinopsis' => 'Bahasa Indonesia untuk SMP/MTs Kelas IX',
                'genre_id' => 2, // Sesuaikan dengan ID di tabel genre_id
                'stock' => 10,
                'gambar_buku' => 'indonesia9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAE',
                'isbn' => '9786024279424',
                'title' => 'Bahasa Inggris',
                'penulis_id' => 2,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'English for Nusantara untuk SMP/MTs Kelas IX',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'english9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAT',
                'isbn' => '9786230955853',
                'title' => 'Informatika',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'informatika9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAM',
                'isbn' => '9786230955853',
                'title' => 'Matematika',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'mat9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAA',
                'isbn' => '9786022447870',
                'title' => 'Ilmu Pengetahuan Alam',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Ilmu Pengetahuan Alam untuk SMP/MTs Kelas IX',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'ipa9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAS',
                'isbn' => '9786230955853',
                'title' => 'Ilmu Pengetahuan Sosial',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'ips9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAN',
                'isbn' => '9786230955853',
                'title' => 'Pendidikan Kewarganegaraan',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'pkn9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
