<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BukuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('buku')->insert([
            [
                'kode_buku' => 'SATUI',
                'isbn' => '9786231183682',
                'title' => 'Bahasa Indonesia',
                'penulis_id' => 1, // Sesuaikan dengan ID di tabel penulis_id
                'penerbit_id' => 1, // Sesuaikan dengan ID di tabel penerbit_id
                'terbit' => '2023-01-01',
                'deskripsi' => 'Bahasa Indonesia: untuk SMP/MTS Kelas VII (Edisi Revisi)',
                'sinopsis' => 'Bahasa Indonesia: untuk SMP/MTS Kelas VII (Edisi Revisi)',
                'genre_id' => 2, // Sesuaikan dengan ID di tabel genre_id
                'stock' => 10,
                'gambar_buku' => 'indonesia7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'SATUE',
                'isbn' => '9786022448853',
                'title' => 'Bahasa Inggris',
                'penulis_id' => 2,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'English for Nusantara untuk SMP/MTs Kelas VII',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'english7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'SATUT',
                'isbn' => '9786230955853',
                'title' => 'Informatika',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'informatika7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'SATUM',
                'isbn' => '9786230955853',
                'title' => 'Matematika',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'mat7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'SATUA',
                'isbn' => '9786231184573',
                'title' => 'Ilmu Pengetahuan Alam',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Ilmu Pengetahuan Alam untuk SMP/MTs Kelas VII (Edisi Revisi)',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'ipa7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'SATUS',
                'isbn' => '9786230955853',
                'title' => 'Ilmu Pengetahuan Sosial',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'ips7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'SATUP',
                'isbn' => '9786230955853',
                'title' => 'Pendidikan Kewarganegaraan',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'pkn7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAIN',
                'isbn' => '9786022446224',
                'title' => 'Bahasa Indonesia',
                'penulis_id' => 1, // Sesuaikan dengan ID di tabel penulis_id
                'penerbit_id' => 1, // Sesuaikan dengan ID di tabel penerbit_id
                'terbit' => '2023-01-01',
                'deskripsi' => 'Yes it is',
                'sinopsis' => 'Bahasa Indonesia untuk SMP Kelas VIII',
                'genre_id' => 2, // Sesuaikan dengan ID di tabel genre_id
                'stock' => 10,
                'gambar_buku' => 'indonesia8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAEN',
                'isbn' => '9786024279417',
                'title' => 'Bahasa Inggris',
                'penulis_id' => 2,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'English for Nusantara untuk SMP/MTs Kelas VIII',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'english8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAIF',
                'isbn' => '9786230955853',
                'title' => 'Informatika',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'informatika8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAMK',
                'isbn' => '9786230955853',
                'title' => 'Matematika',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'mat8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAPA',
                'isbn' => '9786022447948',
                'title' => 'Ilmu Pengetahuan Alam',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Ilmu Pengetahuan Alam untuk SMP Kelas VIII',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'ipa8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAPS',
                'isbn' => '9786230955853',
                'title' => 'Ilmu Pengetahuan Sosial',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'ips8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'DUAPN',
                'isbn' => '9786230955853',
                'title' => 'Pendidikan Kewarganegaraan',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'pkn8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAI',
                'isbn' => '9786022446361',
                'title' => 'Bahasa Indonesia',
                'penulis_id' => 1, // Sesuaikan dengan ID di tabel penulis_id
                'penerbit_id' => 1, // Sesuaikan dengan ID di tabel penerbit_id
                'terbit' => '2023-01-01',
                'deskripsi' => 'Yes it is',
                'sinopsis' => 'Bahasa Indonesia untuk SMP/MTs Kelas IX',
                'genre_id' => 2, // Sesuaikan dengan ID di tabel genre_id
                'stock' => 10,
                'gambar_buku' => 'indonesia9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAE',
                'isbn' => '9786024279424',
                'title' => 'Bahasa Inggris',
                'penulis_id' => 2,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'English for Nusantara untuk SMP/MTs Kelas IX',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'english9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAT',
                'isbn' => '9786230955853',
                'title' => 'Informatika',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'informatika9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAM',
                'isbn' => '9786230955853',
                'title' => 'Matematika',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'mat9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAA',
                'isbn' => '9786022447870',
                'title' => 'Ilmu Pengetahuan Alam',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Ilmu Pengetahuan Alam untuk SMP/MTs Kelas IX',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'ipa9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAS',
                'isbn' => '9786230955853',
                'title' => 'Ilmu Pengetahuan Sosial',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'ips9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'TIGAN',
                'isbn' => '9786230955853',
                'title' => 'Pendidikan Kewarganegaraan',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'Oh some',
                'genre_id' => 2,
                'stock' => 5,
                'gambar_buku' => 'pkn9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'PERKE',
                'isbn' => '97862309558888',
                'title' => 'Perahu Kertas',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => '66 Halaman',
                'sinopsis' => 'Perahu Kertas menceritakan perjalanan dua anak muda, Kugy dan Keenan, yang memiliki impian besar dan keyakinan terhadap dunia mereka masing-masing. Kugy adalah gadis unik yang percaya bahwa dirinya adalah seorang "agen Neptunus" dan senang menulis cerita dongeng yang dituangkan dalam kertas-kertas kecil berbentuk perahu. Di sisi lain, Keenan adalah seorang seniman berbakat yang harus berhadapan dengan tuntutan keluarga untuk meneruskan bisnis mereka.',
                'genre_id' => 1,
                'stock' => 5,
                'gambar_buku' => 'fiksi.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'THEPO',
                'isbn' => '9780062662569',
                'title' => 'The Popy War',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => 'Now what ?',
                'sinopsis' => 'The Poppy War mengisahkan perjalanan Rin (Fang Runin), seorang yatim piatu dari keluarga sederhana di pedesaan yang berhasil masuk ke Sinegard, akademi militer paling prestisius di Kekaisaran Nikara. Berkat kecerdasannya yang luar biasa dan ambisinya yang besar, Rin menempuh jalan sulit untuk mengubah nasibnya, melawan prasangka kelas, dan mengasah kemampuannya.Namun, dunia yang ia masuki penuh intrik politik, perpecahan kekaisaran, dan ancaman perang yang membayangi. Rin menemukan bahwa ia memiliki bakat langka untuk memanipulasi kekuatan mistis yang mematikan, tetapi kemampuan ini membawa konsekuensi yang mengerikan. Saat perang dengan Kekaisaran Mugen pecah, Rin dihadapkan pada pilihan sulit: apakah ia akan menggunakan kekuatan dewa api untuk menyelamatkan negaranya atau membiarkan kekuatan itu menghancurkan dirinya sendiri?',
                'genre_id' => 5,
                'stock' => 5,
                'gambar_buku' => 'fantasi.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'LASPE',
                'isbn' => '97862309558911',
                'title' => 'Laskar Pelangi',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => '529 halaman',
                'sinopsis' => 'Laskar Pelangi adalah kisah inspiratif yang berlatar di sebuah desa kecil di Pulau Belitung, Indonesia. Cerita ini berpusat pada perjuangan 10 anak dari keluarga miskin untuk mendapatkan pendidikan di SD Muhammadiyah, sekolah yang hampir ditutup karena kekurangan murid. Mereka dikenal sebagai "Laskar Pelangi," nama yang diberikan oleh guru mereka, Bu Muslimah, karena semangat dan keceriaan mereka.',
                'genre_id' => 4,
                'stock' => 5,
                'gambar_buku' => 'petualangan.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_buku' => 'NOVKA',
                'isbn' => '9786025508884',
                'title' => 'Kata',
                'penulis_id' => 1,
                'penerbit_id' => 1,
                'terbit' => '2022-06-15',
                'deskripsi' => '350 halaman',
                'sinopsis' => 'Biru Laut, seorang pemuda yang sederhana dan penuh semangat, menyimpan perasaan mendalam terhadap sahabat masa kecilnya, Kata Kanaya. Namun, perasaan itu terpendam selama bertahun-tahun tanpa keberanian untuk diungkapkan. Kata, di sisi lain, tidak pernah menyadari betapa besar arti dirinya bagi Biru.',
                'genre_id' => 3,
                'stock' => 5,
                'gambar_buku' => 'romantis.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
