// import './bootstrap';
// import '../../public/client/js/kode/buku';
import './datatable/supplier';
import './datatable/users';
import './datatable/buku';
import './datatable/admin';
import './datatable/peminjaman';
import './datatable/permintaan';
import './datatable/penerbit';
import './datatable/penulis';
import './datatable/genre';
import './kode';
